name: Compile LaTeX
on: [push]
jobs:
  upload_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: patch-frame-note.tex
          latexmk_use_xelatex: true
      - run: mkdir pdf && cp patch-frame-note.pdf pdf
      - name: Upload pdf on GitHub pages
        id: deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: pdf